# Generated by Django 5.2.11 on 2026-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
